theme = "sonokai"

[editor]
line-number = "relative"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
bufferline = "always"
idle-timeout = 0
true-color = true
mouse = false

[editor.cursor-shape]
insert = "bar"
normal = "bar"
select = "underline"

[editor.lsp]
display-inlay-hints = false

[editor.indent-guides]
render = false


